#!/usr/bin/env bash
# This script kills the 7-highlander process using SIGKILL

pids=$(pgrep -f 7-highlander)

if [ -n "$pids" ]; then
  # Use xargs to handle multiple PIDs safely
  echo "$pids" | xargs -r kill -9
fi
